# Le champ robot_id est à modifier pour chaque robot
# Remarque : Le champ robots_ips est à modifier
robots_ips:
  0 : 192.168.1.26
  1 : 192.168.1.26
  2 : 192.168.1.26
  3 : 192.168.1.26
  4 : 192.168.1.26
robot_id: 1
port : 65432